server:
  host: "localhost"
  port: 8094
  timeout: 15
  idle_timeout: 30

database:
  username: "postgres"
  password: "password"
  host: "localhost"
  port: 5433
  dbname: "spaymanager"

log:
  level: "info"
